### ISSUE TITLE
Saving/ending the randomization

### ISSUE THREAD

**Issue by Swift1304** [Ajarmar/universal-pokemon-randomizer-zx#15] opened 2020-09-28 08:58 UTC
![ZXissue](https://user-images.githubusercontent.com/72012166/94411713-cb144400-0170-11eb-9a75-ddc6a8810fb4.JPG)

This randomizer looks amazing if it really does all of this and just what the community has been waiting for.
However, I loaded in a X.3ds rom and filled in various tick boxes, clicked randomize save and then it was stuck on it for over 1 hour (see image). 

I am familiar with randomizing using pk3ds so know it can take a bit of time but it should be much faster than that?

Do you not have to unpack the .3ds rom file at all to use this? Or does the executable extract/unpack and then rebuild the rom after randomizing itself?

Thanks!

**Comment by tom-overton** [comment] 2020-09-28 10:33
It should be significantly faster than one hour, yes. On my machine, it takes somewhere between 30-35 seconds to save Pokemon X as a CXI and fewer than 5 seconds to save it as a LayeredFS, and this is with tons of options enabled to slow it down as much as possible. We've heard reports about really slow saving and loading times, but we haven't been able to reproduce it ourselves or really understand why it's so slow. Users that have reported two different things that seem to help with slow loading and saving:
1. Running the randomizer by using the launcher.jar application, rather than by using the PokeRandoZX.jar application (we recommend in the README to use launcher.jar, but some habits are hard to break)
2. Updating Java. What this *specifically* entails, I'm not exactly sure, because no one has told us what version they were running before they updated. This page shows how to find your current version; it should *at least* be Version 8, if not higher: https://www.java.com/en/download/help/version_manual.html

If neither of these resolve the issue, let me know.

As for your second question, no, you don't have to unpack the ROM file. The randomizer handles extracting game files and rebuilding the ROM for you. If you've ever used Universal Pokemon Randomizer with any of the Gen 1-5 games, we want the experience to be familiar with the 3DS games.

**Comment by tom-overton** [comment] 2020-10-06 19:03
Closing this, since it's been about eight-and-a-half days with no further comment. If you have the same issue still, you can feel free to reopen. Like I said in the above comment, it's probably something that can be fixed by using launcher.jar or by using an updated version of 64-bit Java.

**Closed by tom-overton** 2020-10-06 19:03 UTC
