### ISSUE TITLE
new uprandomizer freezes on a black screen after first rival battle. it also freezes if you want to check your starter after you received one.[Bug] 

### ISSUE THREAD

**Issue by smokincube** [Ajarmar/universal-pokemon-randomizer-zx#170] opened 2021-04-22 21:58 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by tom-overton** [comment] 2021-04-23 00:18
Can you please provide more information such as:
- What game were you attempting to randomize?
- What version of the randomizer are you using?
- Can you provide a log file for a seed that demonstrates this issue?

**Comment by smokincube** [comment] 2021-04-23 00:35
i was attempting to randomize pokemon y.
Randomizer Version: 4.1.0.
i can't provide you with a log file the demonstrates this issue because i deleted the file itself because of the freeze.
I made 3 seperate files and was about to play it with friends and all 3 of us had the same issue it happens after receiving your starter.

**Comment by tom-overton** [comment] 2021-04-23 00:41
Can you try making a new seed and sending the log over if the issue reproduces? Additionally, can you see if you have a game update installed by looking for something like "Ver 1.5" on this screen?

![image](https://user-images.githubusercontent.com/12245827/112219441-33a12280-8be2-11eb-881d-1142ebb01e82.png)

**Comment by smokincube** [comment] 2021-04-23 01:45
i can try that out once i try to do pokemon y again. I randomized it with pk3ds now so me and my friends could still play once we have finished i will try again. I did try out both alpha and omega and both seem to be working fine. either way thankyou for your reply!

**Comment by tom-overton** [comment] 2021-04-23 17:46
I hope this doesn't sound too imposing, but can you please try it soon? I want to make sure that if there's an issue with the randomizer, it gets addressed quickly. If this isn't something you're going to look into soon, then I'll just close this issue for now, since I can't replicate the problem on my own copy of Pokemon Y using 4.1.0.

**Comment by smokincube** [comment] 2021-04-23 20:34
aight I will do it a bit later this evening if you don't mind i will try to make a log for the seed aswell!

**Comment by smokincube** [comment] 2021-04-24 14:14
[upycostum.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6369754/upycostum.cxi.log)

It happened again right after the first rival battle. 
Could you please take a look?

**Comment by tom-overton** [comment] 2021-04-26 08:44
Are you playing some sort of ROM hack? Comparing my own ROM Diagnostics to yours, I see some pretty noticeable differences:

Mine:
```
.code: D0F07ED8
romfs header: 82137600
DllField.cro: 9575E9CD
DllPoke3Select.cro: 2A592492
a/0/1/2: C4BF77F6
a/0/3/8: 7C3D4F79
a/0/4/0: 9CC8CE76
a/0/7/4: D82C84F1
a/2/1/4: 165E653E
a/2/1/5: B6F5DFA9
a/2/1/8: 7834E6AE
```

Yours:
```
.code: 46BDAD57
romfs header: 7474BC24
DllField.cro: 8160B8B4
DllPoke3Select.cro: 50F40B56
a/0/1/2: 41311E99
a/0/3/8: 13271B37
a/0/4/0: 9820FC7E
a/0/7/4: 4BCD8ECE
a/2/1/4: 4ECC4A49
a/2/1/5: C98A6D28
a/2/1/8: F0999384
```

**Comment by smokincube** [comment] 2021-04-26 13:30
this was indeed a rom hack with costum form pokemon i also tried it with a regular file of y with the same result though. This rom hack was made by 8bitbro's and it works if you randomize it with pk3ds.

**Comment by tom-overton** [comment] 2021-06-16 19:28
Sorry, but we don't support ROM hacks. We don't know what things have changed in the hack, so we can't guarantee that any specific thing that they've changed is going to work with the randomizer. We touch more things in the ROM than pk3DS does, so it working fine in pk3DS is no indication that it will work with our randomizer.

**Closed by tom-overton** 2021-06-16 19:28 UTC
Labels: bug
