### ISSUE TITLE
[Help] it tell mi that i cannot randomize because im need a version but i already using that version so i dont know how can i do

### ISSUE THREAD

**Issue by pokepini** [Ajarmar/universal-pokemon-randomizer-zx#257] opened 2021-07-27 19:35 UTC
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version:

**If your problem is that you can't randomize a game:**
![pokemon sdad](https://user-images.githubusercontent.com/88057149/127216682-0eb7bbac-8ea6-4c50-a40a-e50fb2e0e85f.PNG)

**Comment by pokepini** [comment] 2021-07-27 19:36
someone HELP MEEEEE

**Comment by tom-overton** [comment] 2021-07-28 07:13
Did you start the randomizer by double-clicking on launcher_WINDOWS.bat? This message *should* go away if you do that.

**Comment by tom-overton** [comment] 2021-08-05 18:15
I'm gonna close this issue since it seems like the problem is resolved just by using the launcher. Let me know if you run into any other issues.

**Closed by tom-overton** 2021-08-05 18:15 UTC
