### ISSUE TITLE
Random every level causing single loop across numerous pokemon[Bug] 

### ISSUE THREAD

**Issue by thor611** [Ajarmar/universal-pokemon-randomizer-zx#478] opened 2022-07-02 03:41 UTC
**Describe the bug**
Numerous different pokemon getting stuck in a single, large evolution loop on random every level setting. Even random wild pokemon caught that are not part of the loop evolve normally a couple of times and also wind up on the loop. Hacked in rare candies, having heard those help break such loops, still no luck getting out of it. 

**To Reproduce**
1. See attached files for both my used config settings and two .savs of my file, both for Fire Red. Using version 4.4.0, as 4.5.0 is unable to write randomized files for me for some reason (unhandled java exception, happy to provide more info on that if desired.)
2. Load my saves, or randomize another file with included settings.
3. One save, firered3.sav, was basically where I organically got to. Firered3synced.sav is intended to more easily demonstrate the problem, as I've synchronized all 3 pokemon in my party on the electabuzz step of the loop. All 3 pokemon were caught as different base forms on different routes. 
3. Hack in some rare candies, test away (included files already have unlimited rare candies in the PC).
4. Notice evolution looping. Sequence is something like zapdos -> electabuzz -> venomoth -> mew -> corphish -> machamp -> celebi -> surskit -> illumise -> torkoal -> feraligatr -> zapdos 

**Expected behavior**
Random evolution every level setting randomizing evolutions every level.

**Screenshots**
Hard to demonstrate with screenshots, given the nature of the problem. It occurs over the course of about 11 levels. 

**System (please complete the following information):**
 - Operating System: Windows 10 64-bit
 - Java Version: Version 8 Update 333
 - Randomizer Version: 4.4.0

**Additional context**
I heard about and witnessed this bug for the first time on a GDQ run, one of the runners having reported experiencing it regularly as well. His solution is use rare candy, which for him breaks the loop. It does not break the loop for me, leaving me in effect playing with ~11 pokemon options rather than the random and chaotic experience I was hoping for. 

Did some more testing, and managed to find another pair of loops. Maybe I just got unlucky with having so many of my initial pokemon all on the same track, though the second loop I found covers all but one of the other pokemon species I managed to find, which is a third and on its own 4-step loop.

[pokerandogit.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9032363/pokerandogit.zip)

**Comment by FrostedGeulleisia** [comment] 2022-07-02 08:23
Rare Candies breaking the loop are a Speedchoice feature, not a randomizer feature.
(Speedchoice being the hack used for races)

**Comment by tom-overton** [comment] 2022-07-02 23:20
Evolution loops are entirely expected with this feature; I just pushed up a commit (d9e34bd857477bea7ad1a2c4c63c491aef10647a) explaining that it's intentional. I'm not sure what the GDQ run was using (given @FrostedGeulleisia's comment, it was probably Speedchoice), but "breaking the loop" with a rare candy has never been a part of this randomizer either.

I'm going to close this issue, since it's not actually a bug and is entirely expected behavior. If you want to open a new issue for that v4.5.0 thing, though, feel free.

**Closed by tom-overton** 2022-07-02 23:20 UTC
Labels: bug
