### ISSUE TITLE
[Help] Randomizing a randomized file B/W v4.2 

### ISSUE THREAD

**Issue by denaggels** [Ajarmar/universal-pokemon-randomizer-zx#220] opened 2021-06-13 21:50 UTC
I just finished a randomized 5 player nuzlocke in Pt. 
We all use the same randomized enemies, pokemon and items (etc.), except for static pokemon.

I accomplished this by **creating a randomized file and using this file to create 4 more** files changing only the static pokemon.

Now I tried this again with Pokemon Black, but all the secondary files (files that used the first randomized game as a input and only randomized static) **encounter a black screen when clicking on "new game".** 

I did some testing and found out: even without changing anything, the black screen happens. (Using the Randomized file as rom input and "randomizing" again, without anything being randomized).
**This does not happen with v4.1, but with the most recent v4.2** of the randomizer (using IntelliJ IDEA, as shown in the wiki).
The first randomized file works.

 - Operating System: Windows 10
 - Randomizer Version: 4.2 (13.06.21)

Usually I wouldn't bother reaching out, as this is surely no ordinary request. But seeing it work on v4.1, but not on v4.2 made me wonder.
Please let me know, if there is something I can test, or help contributing.

**Comment by denaggels** [comment] 2021-06-13 21:57
I just randomized a file with 4.2 and used the new file to randomize statics with 4.1. This seemingly worked, as there was no black screen. Couldnt check trainer held items, or statics, but the starters are the same randomized pokemon as before.

**Comment by denaggels** [comment] 2021-06-13 22:33
Just speedran through the first portion of the game. 
Everything worked as intended with first using 4.2 and putting that file into 4.1 and randomizing only statics.
No Blackscreen, statics are twice randomized, other pokemon once randomized, shops random, trainer held items are random. 
Perfect workaround, but I am still here to test, if you need me

**Comment by tom-overton** [comment] 2021-06-13 22:50
What you're trying to do isn't supported so I'm not surprised it doesn't work. However, I'm also decently sure I know the cause of it. When you perform the randomization of statics in v4.2.0, you have "Fix Music" turned on, don't you? Try again with that off.

**Comment by denaggels** [comment] 2021-06-14 11:15
I know, that this is not something that I exspected to be supported, but since it worked with Platinum and with black on v4.1 i thought I would tell you guys, because I suspect it could be helpfull to know this changed, when looking for other errors.

I dont remember turning it on, and as I tried testing right now, I noticed I cant even turn on "Fix Music" in pokemon black (german version btw). Screenshot follows as proof. 
![Pokemon black rando Static setting music](https://user-images.githubusercontent.com/81873853/121883466-1166fe80-cd12-11eb-9c9a-3706b2b741ff.png)

**Comment by tom-overton** [comment] 2021-06-14 18:58
Huh, interesting. I know that the patch we do for Fix Music would break if you applied it twice so that was my guess. Does this reproduce with *only* statics changed (in other words, with *only* the thing in your screenshot)? Or do other settings need to be on too? If other settings need to be on, can you send your settings string over?

**Comment by denaggels** [comment] 2021-06-16 14:32
I just "randomized", but didnt change anything twice. And still the blackscreen appeared. 

Just to clearify what I did:

1 .Open Randomizer v4.2 via IntelliJ IDEA
2. Load Pokemon Black (german)
3. immediately press Randomize (Save), without adjusting any settings
4. load the "randomized" file
5. repeat step 3

file from step 3 works fine, file from step 5 results in a black screen when clicking on "new game" after booting.

**Comment by Ajarmar** [comment] 2021-06-16 19:28
Closing this since it's about an unsupported functionality. Thanks for the input anyway.

**Closed by Ajarmar** 2021-06-16 19:28 UTC

**Comment by denaggels** [comment] 2021-06-16 21:08
alright, hope this helps with some other bug in the future at least.
just read the changelog - could it be the intro pokemon from the professor? eventhough nothing should get changed

**Comment by tom-overton** [comment] 2021-06-17 01:20
It is indeed the intro Pokemon. The randomizer applies a patch in order to make the intro Pokemon whatever we want; you can see the patch here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/blob/master/src/com/dabomstew/pkrandom/romhandlers/Gen5RomHandler.java#L2931

If you want to make this work, just comment out this whole patch and recompile; you won't be able to randomize intro Pokemon, but you should be able to do what you want without the game crashing. Alternatively, you can play BW2 instead, which doesn't need the patch.

**Comment by denaggels** [comment] 2021-06-17 08:12
Thank you for looking into that! I am thrilled to have learned, where that problem came from.

As I wrote in my post, I already got my workaround to work, so for the time being I don't need that "trick". Thank you for the heads up though, it still might come in handy some time 😄  
And good to know that BW2 works, that will be our next game to 5-player-soullink-nuzlocke 😆
