### ISSUE TITLE
Area 1-to-1 Mapping does not work with Allow Alternate Forms in Gen 6 games

### ISSUE THREAD

**Issue by Alxprit** [Ajarmar/universal-pokemon-randomizer-zx#83] opened 2020-12-23 02:29 UTC
I feel like I remember people talking about this kind of issue happening previously with Global 1-to-1 Mapping, but maybe whatever fix was applied for that didn't apply to Area 1-to-1. Running the randomization with that setting results in a file that crashes when loaded in Citra, and without Allow Alternate Formes checked it works just fine. I find this pretty lame because without that I can't take advantage of cool things like permanent Mega Evolutions in the wild in Gen 6 games. If this has already been resolved then let me know what I can do to fix it, otherwise I hope there'll be a fix soon.

Thank you for your time reading this in any case!

**Comment by tom-overton** [comment] 2020-12-23 12:29
I have no issues with this combination:
![f](https://user-images.githubusercontent.com/12245827/102996175-75350b00-44d7-11eb-9156-9df56c898b34.png)

Please provide a log file demonstrating the issue if you can reproduce it.

**Comment by Alxprit** [comment] 2020-12-23 16:30
[alphasapphirerandom.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5736191/alphasapphirerandom.cxi.log)
Here's the failed randomization's log. It could be that it only applies to Omega Ruby and Alpha Sapphire.

**Comment by tom-overton** [comment] 2021-01-04 08:22
I got around to trying this and I can't seem to replicate what you're seeing. When you say it "results in a file that crashes when loaded in Citra," what does that mean? Does it crash the instant you attempt to load it into the emulator? Does it crash when you load into a particular section of the game? Because I generated CXI and LayeredFS output using the same seed and settings and I'm not crashing at all.

**Comment by Alxprit** [comment] 2021-01-11 04:49
I'm sorry I haven't gotten back to this. I genuinely don't know what the issue is. I will say that the crash was immediate, and that trying to use the LayeredFS settings resulted in an unrandomized ROM. Maybe something very specific failed for no particular reason and it's just a bizarre occurance for me. But if you can get it to work on OR/AS then I must be doing something wrong somewhere.

**Comment by tom-overton** [comment] 2021-01-11 11:39
Hm, if it's crashing immediately, can you try uploading your Citra log file? Here's a guide from Citra on how to get it: https://community.citra-emu.org/t/how-to-upload-the-log-file/296

Note that if you reopen Citra *after* it crashes, then your log will be overwritten with a clean one. So make sure that once it crashes, you don't open it again until you upload the log here.

**Comment by Ajarmar** [comment] 2021-02-19 23:50
@Alxprit Are you fine with not troubleshooting this further? If so, I'll close the issue.

Notably we've seen a lot of weird errors with Alpha Sapphire in particular so this could be due to a bad ROM. You could try using a different ROM and see if that works (either with a different game or a different ROM of the same game).

**Comment by Alxprit** [comment] 2021-02-27 17:54
I apologize, I felt kind of dumb for suggesting something that may have not been an issue at all, so I haven't checked this out. I will try and get the log file at least, but it may take a bit.

**Comment by Ajarmar** [comment] 2021-02-27 21:56
No need to feel dumb about it, if something doesn't work then there's clearly a problem somewhere (even if it may end up not being our program's fault). I'll keep the issue open for now so just post the stuff when you can

**Comment by Alxprit** [comment] 2021-05-13 17:03
[citra_log.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6473960/citra_log.txt)

Sorry it took so long, again. Really no excuse for it other than skewed priorities. But here's the log, hopefully it'll reveal what the exact issue is.

**Comment by tom-overton** [comment] 2021-06-17 23:27
@Alxprit Sorry for taking so long to look into this on my end as well. I took a look at the logs and the crash seems to be occurring in an area of the code we don't touch at all. Can you try this again using [the latest release](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.0) of the randomizer? If it still doesn't work, can you post the *randomization* log here? Starting with 4.1.0, we started logging some diagnostic information about the ROM in the randomization log. With that, I can see information about your ROM and hopefully track down the issue further.

**Comment by tom-overton** [comment] 2021-08-30 08:04
After committing af2181755393cf0b7ae961939f8024b12a030a5c, I was 99% sure that this bug was caused by the same fundamental issue. I retested your example, and sure enough, I produced a CXI that crashed *before* this commit and produced a CXI that worked fine *after* this commit. The reason I didn't notice that before is because I was just doing layeredFS output, which doesn't compress the executable.

I'm going to close this out because I'm almost sure I fixed the underlying issue. Please use layeredFS output until the next release to avoid this issue.

**Closed by tom-overton** 2021-08-30 08:04 UTC
