### ISSUE TITLE
NullPointerException when loading Alpha Sapphire rom file

### ISSUE THREAD

**Issue by Afterlyte** [Ajarmar/universal-pokemon-randomizer-zx#11] opened 2020-09-27 04:57 UTC
I've seen other people have this same issue on Twitter when trying to load ORAS rom files specifically. When opening the rom file, a dialogue box pops up saying there was an issue loading the rom, and outputs the attached error log file.

I have tested a Y, Moon, and Ultra Moon rom file and all three of those worked fine.
[error_2020-09-26-21-53-15.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5287746/error_2020-09-26-21-53-15.txt)

**Comment by tom-overton** [comment] 2020-09-27 05:35
I believe that 828473bd47e and 575bf4296ff fix this, and if not, then f6a13ec561708 will provide a better error message. These will be out in the next release so you can try them yourself.

If you want to try and unblock yourself now before the next release and are comfortable with a hex editor, try this: if you have a .3ds input file, go look at offset 0x418F and see if it's 0x04. If it's *not*, then set it to 0x04 and try to load the file again. The problem is that the current release is very strict about detecting whether a game image is decrypted. I assumed that *every* decryption program would set the byte in the header that indicates the game image is decrypted...but it turns out a decent number of users have a decrypted ROM that *doesn't* have this byte set. Those commits I posted above will relax this strict checking a bit.

**Comment by Afterlyte** [comment] 2020-09-27 05:43
> 
> 
> I believe that [828473b](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/commit/828473bd47e76600d2acd291aa75dc3c1d6ab6cd) and [575bf42](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/commit/575bf4296ff10828e211bde0424fae66c6414387) fix this, and if not, then [f6a13ec](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/commit/f6a13ec5617081c12879e50cc38f8f4802f43e45) will provide a better error message. These will be out in the next release so you can try them yourself.
> 
> If you want to try and unblock yourself now before the next release and are comfortable with a hex editor, try this: if you have a .3ds input file, go look at offset 0x418F and see if it's 0x04. If it's _not_, then set it to 0x04 and try to load the file again. The problem is that the current release is very strict about detecting whether a game image is decrypted. I assumed that _every_ decryption program would set the byte in the header that indicates the game image is decrypted...but it turns out a decent number of users have a decrypted ROM that _doesn't_ have this byte set. Those commits I posted above will relax this strict checking a bit.

This worked perfectly, thank you so much for giving me the technical details for fixing that!

**Comment by tom-overton** [comment] 2020-09-27 05:49
I'm glad it worked for you! Since the issue is related to our overly-strict decrypted ROM handling, and since I've fixed that for the next release, I'll close this issue for now. If you see similar problems in the next release, though, feel free to reopen and I'll be happy to take a look!

**Closed by tom-overton** 2020-09-27 05:49 UTC
