### ISSUE TITLE
It won't load

### ISSUE THREAD

**Issue by RialosOfAstora** [Ajarmar/universal-pokemon-randomizer-zx#57] opened 2020-11-09 03:16 UTC
I made sure to that Java was in the right directory like the guide said but I try to open it with Java and it just doesn't happen. I don't get an error message or anything like that, it just doesn't happen

**Comment by Ajarmar** [comment] 2020-11-18 19:48
Please make sure that you have a compatible version of Java installed. Read this page for more information: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java

**Comment by kianonthemoon** [comment] 2020-11-20 04:07
I don't know if I'm having the same issue as OP but I verified my version of Java according to the guide and everything should check out but I keep getting "Error: Unable to access jarfile PokeRandoZX.jar." I'm on Mac and I try to manually use terminal to boot the randomizer with "java -Xmx4096M -jar /Users/(my username)/Downloads/PokeRandoZX-v4_0_2/PokeRandoZX.jar" and that starts the randomizer but still won't let me load 3DS roms.

**Comment by Ajarmar** [comment] 2020-11-20 22:23
@kianonthemoon Weird, I'm not sure what could be causing that. Could you try extracting the zip file to somewhere that isn't in your Downloads folder, and see if that works?

**Comment by kianonthemoon** [comment] 2020-11-21 05:04
> @kianonthemoon Weird, I'm not sure what could be causing that. Could you try extracting the zip file to somewhere that isn't in your Downloads folder, and see if that works?

I tried this and it still gave me the same error. I think the problem is that the launcher.jar is written to specifically run "java -Xmx4096M -jar PokeRandoZX.jar" and for Macs at least you have to have the file path defined to run the command. When I do "java -Xmx4096M -jar /Users/(Username)/Desktop/PokeRandoZX-v4_0_2/PokeRandoZX.jar" then the randomizer actually opens but tells me it won't let me open .cias because I get an alert saying I didn't open the randomizer with the launcher. I don't know, maybe that's just some wishful thinking since I can hardly call myself a coder

**Comment by kianonthemoon** [comment] 2020-11-21 05:09
> > @kianonthemoon Weird, I'm not sure what could be causing that. Could you try extracting the zip file to somewhere that isn't in your Downloads folder, and see if that works?
> 
> I tried this and it still gave me the same error. I think the problem is that the launcher.jar is written to specifically run "java -Xmx4096M -jar PokeRandoZX.jar" and for Macs at least you have to have the file path defined to run the command. When I do "java -Xmx4096M -jar /Users/(Username)/Desktop/PokeRandoZX-v4_0_2/PokeRandoZX.jar" then the randomizer actually opens but tells me it won't let me open .cias because I get an alert saying I didn't open the randomizer with the launcher. I don't know, maybe that's just some wishful thinking since I can hardly call myself a coder

Oh found a quick fix. I moved the PokeRandoZX.jar to my Users/(Username) folder and the launcher finally worked. I guess that was the assumed path

**Comment by bbroo1** [comment] 2020-11-21 09:22
I can open the program using the command promt but this does of course not allow me to randomise my rom. When I use the launcher I get a flash of a command prompt like screen running java.exe which than closes and nothign further happens. I checked in the command promt and have the latest 64-bit version of java. Any ideas on how I can fix this?

**Comment by Ajarmar** [comment] 2020-11-21 11:02
@kianonthemoon Good that you found a fix for it. This definitely seems like a Mac specific issue (although we've had people who have been able to run the launcher on Mac before, so it could even be an issue with a specific macOS version). This issue should be fixed in the next release of the randomizer.

@bbroo1 The launcher should create a file called `launcher-log.txt` when you try to start it. Have you tried reading it, and if so, what does it say?

**Comment by bbroo1** [comment] 2020-11-21 11:47
@Ajarmar it does not generate the launcher-log.txt file. When running the program from the command prompt it does generate a config file which states: 
checkedcustomnames=true
checkedcustomnames172=false
firststart=4.0.2

**Comment by Ajarmar** [comment] 2020-11-21 11:56
What happens if you run the launcher from the command prompt with `java -jar launcher.jar`?

**Comment by bbroo1** [comment] 2020-11-21 13:21
That works, awesome thank you, can not believe I did not think of that :P

**Comment by tom-overton** [comment] 2020-12-07 21:54
@RialosOfAstora Did you ever get this working? You're the only person in this thread that hasn't gotten their issue resolved, and it's been a month since this was opened. I just want to check in and make sure you eventually managed to open the randomizer.

**Comment by tom-overton** [comment] 2020-12-14 19:46
Closing this due to lack of activity from OP. Feel free to revive this issue if you want

**Closed by tom-overton** 2020-12-14 19:46 UTC
