### ISSUE TITLE
[Bug] Virtual Console Version of Crystal Not Supported

### ISSUE THREAD

**Issue by ForeverEndeavor** [Ajarmar/universal-pokemon-randomizer-zx#297] opened 2021-09-23 16:04 UTC
**Describe the bug**
Attempting to apply a randomization to the Virtual Console version of Crystal fails with the following error snippet:

```
java.lang.ArrayIndexOutOfBoundsException: 252
	at com.dabomstew.pkrandom.romhandlers.Gen2RomHandler.getTrainers(Gen2RomHandler.java:864)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomizeTrainerPokes(AbstractRomHandler.java:1575)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:334)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$105(NewRandomizerGUI.java:880)
	at java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
1. Load Virtual Console version of Crystal
2. Set randomization options in UI
3. Attempt to apply randomized settings to game
4. Receive "There was an unhandled exception trying to save your ROM to disk" error message

**Expected behavior**
The ROM should be randomized

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 1.8.0_301, Java HotSpot(TM) 64-Bit Server VM
 - Randomizer Version: 4.2.1

**Additional context**
This error is generally seen when users attempt to apply randomizations to unsupported ROM hacks, but the Virtual Console version of Crystal is an official release, so support for it would be wonderful.

[error_2021-09-23-10-59-33.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7219136/error_2021-09-23-10-59-33.txt)

**Comment by tom-overton** [comment] 2021-09-24 00:00
The Virtual Console release (at least here in the US) is byte-for-byte identical to the US 1.1 retail release of Crystal. I confirmed this myself by extracting the game (at romfs/rom/CGBBYTE1.784). It works fine in the randomizer because it just *is* the original GB release with no modifications.

What you're loading into the randomizer is somehow different from this (the CRC is C3B4CD97 instead of 3358E30A like my ROM/the original U 1.1 release), so I'm not sure where exactly you got that from. At least from my perspective, what you're asking for already works fine.

**Comment by ForeverEndeavor** [comment] 2021-09-24 13:40
Interesting... my initial assumption for why it would be different is, from my understanding, the VC version of Crystal was patched to allow for the GS Ball event to happen after defeating the Elite Four vs. as a Japanese-exclusive event, which may have caused a change in the CRC (although this is probably incorrect).

The ROM in particular was the eShop GBC VC version `Pokemon Crystal (CTR-N-QBRA) (UE).cia` If you mount the CIA file and extract the ROM, this is what is seen:

```
0000.00000002/romfs/rom/CGBBYTE1.784 (2.00 MB - 3358E30A)
```

**Comment by tom-overton** [comment] 2021-09-24 16:59
The patches are actually in the romfs itself; you can see the one for the US version at 0000.00000002/romfs/CGBBYTE1.784.patch. They're applied dynamically at runtime by the emulator.

I'm just going to close this out because I think we've reached the same conclusion: the ROM present in the US version has a CRC of 3358E30A and is a byte-for-byte replica of the US 1.1 release of Crystal, which already supported in the randomizer. I'm not sure what you were loading that had a CRC of C3B4CD97, but loading CGBBYTE1.784 should work fine.

In terms of actually supporting the full Virtual Console .cia, that's just not happening. The randomizer currently assumes that each game corresponds to a particular type of ROM (an assumption that is true outside of the Virtual Console releases), and untangling that just to support something that you can *already* extract the ROM out of doesn't feel like a worthwhile investment of time. In addition, we'd need to perform testing to ensure that the aforementioned patches don't break things once randomized, and we just aren't interested enough to do extensive testing on it.

**Closed by tom-overton** 2021-09-24 16:59 UTC
Labels: bug
