### ISSUE TITLE
[Bug] The launcher encountered an error. Error message can be found in launcher-log.txt. Most likely, the launcher failed because you have an incompatible version of Java

### ISSUE THREAD

**Issue by ItsKee** [Ajarmar/universal-pokemon-randomizer-zx#380] opened 2022-01-25 01:01 UTC
Any time I try to use the launcher, i get this error message. 

This is all the launcher-log.txt says:

Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by tom-overton** [comment] 2022-01-25 01:39
The error message is telling you exactly what the problem is; you have 32-bit Java installed, and you need 64-bit Java installed to use the randomizer. For more information, see the [Java page on our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).

Also, it sounds like you're using an older version of the randomizer. While it won't fix your problem, you should probably upgrade to [v4.3.0](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0) too while you're at it.

**Closed by tom-overton** 2022-01-25 01:39 UTC
Labels: bug

**Comment by ItsKee** [comment] 2022-01-25 01:54
> The error message is telling you exactly what the problem is; you have 32-bit Java installed, and you need 64-bit Java installed to use the randomizer. For more information, see the [Java page on our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).
> 
> Also, it sounds like you're using an older version of the randomizer. While it won't fix your problem, you should probably upgrade to [v4.3.0](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0) too while you're at it.

Ok awesome. Sorry, I don't speak code lol
