### ISSUE TITLE
Randomized HeartGold ROM isn't detected as AP patched by TwilightMenu++ [Bug] 

### ISSUE THREAD

**Issue by barroer** [Ajarmar/universal-pokemon-randomizer-zx#249] opened 2021-07-17 10:42 UTC
**Describe the bug**
Apparently, using the Randomizer does something to the AP patch of my HeartGold ROM, as TwilightMenu++ (v.21.1.1) gives me an Anti-Piracy warning on the randomized ROM, whereas it boots normally with the same ROM before randomizing it. Moreover, TwilightMenu++ has a built-in AP patch for the randomized ROM but it doesn't seem to detect it either. I wish the ROM worked fine, but the one that gives the Anti-Piracy Warning often crashes on black screen upon entering houses or ending battles.

**To Reproduce**
1. Boot your normal HeartGold ROM using TwilightMenu++ (v.21.1.1), see that it works just fine with no Anti-Piracy warning.
2. Randomize your ROM using Pokemon Randomizer ZX
3. Boot the randomized HeartGold ROM using TwilightMenu++ (v.21.1.1), see that it gives you the Anti-Piracy warning and that it crashes.

**Expected behavior**
I thought that randomizing the ROM would keep the AP patch in the ROM, but apparently it doesn't...? and I think that's an error moreso than the expected behavior, but I am not sure.

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: Version 8 Update 291
 - Randomizer Version: v.4.2.1

**Additional context**
I have found a thread (linked at the end of the post) where they give a solution to a similar problem, and I haven't tried this fix because the crashes occur randomly and I could just play for some time and not encounter a crash with the problem still not fixed. What makes me thing that my problem might be different from the one in the other thread is that they never state that they have an Anti-Piracy Warning message, whereas it appears to me and it may be the problem since it only appears after randomizing the ROM.

The thread in question is this one: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/63#issuecomment-729349097

**Comment by barroer** [comment] 2021-07-17 16:19
UPDATE: I have tried playing it on DS Mode, but the crashes still happen.

**Comment by DatXFire** [comment] 2021-07-18 02:10
The devs aren't overly familiar with TM++ so I'll see if I can reproduce myself in a bit. My go to solution when I was playing these years ago was always to first manually patch a rom with the AP patch and then feed that into the randomizer, but if TM++ is correctly identifiying the ROM and in theory AP patching it then I would expect the result to be the same. I'll return with results eventually.

**Comment by barroer** [comment] 2021-07-18 09:04
Good morning, luckily enough I have found a fix to this problem, which I will post on GBAtemp today as a guide, I will close this after I link the guide when I'm done with it.

**Comment by tom-overton** [comment] 2021-08-29 10:28
Did you ever make the guide? This bug is getting a little old so I want to make sure this gets resolved.

**Comment by tom-overton** [comment] 2021-10-04 10:42
It's been more than a month since I asked for an update and more than two-and-a-half months since the last update from the OP, so I'm just going to close this. @barroer If you did end up making a guide, feel free to post it here.

**Closed by tom-overton** 2021-10-04 10:42 UTC
Labels: bug
