### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Eizzah21** [Ajarmar/universal-pokemon-randomizer-zx#150] opened 2021-04-01 16:24 UTC
Hi, so the Randomization just doesn't work on French Pokémon White ROMs, like at all. If I try to randomize the ROM, it just becomes unusable, and displays a whitescreen on Desmums if I try to open it.

1. Randomize a French Pokémon White ROM
2. The randomization should display a success
3. Open the ROM in Desmume

By the way the issue was already there on the old Universal Pokémon Randomizer as well

I'm on a Windows 10 PC, I use Desmume 0.9.11 and v4.1.0 of your randomizer

**Comment by Eizzah21** [comment] 2021-04-01 16:56
Oh and by the way, French Pokémon Black ROMs have worked fine for years, but for whatever reason White doesn't

**Comment by Ajarmar** [comment] 2021-04-01 16:59
Can you upload a randomization log? If you saved a log for the randomized ROM that doesn't work for you, just upload that here. Otherwise, randomize a new one with the same settings and save a log after the randomization finishes.

It's likely that there's some specific setting that causes the problem, so this will make it easier for us to debug.

**Comment by Eizzah21** [comment] 2021-04-01 19:03
[m.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6245906/m.nds.log)
Here is the log for 1 rando I made
Let it be known I tried to make a seed file, but it didn't work
I can send you the rom if you ever want

**Comment by Ajarmar** [comment] 2021-04-02 18:16
Thanks. I managed to find the cause, so this'll be fixed in the next release.

**Closed** 2021-04-02 18:18 UTC
Labels: bug
