### ISSUE TITLE
"ROM is not Supported"

### ISSUE THREAD

**Issue by ProphecyzZ** [Ajarmar/universal-pokemon-randomizer-zx#65] opened 2020-11-20 07:59 UTC
Hello!  When trying to open  .cxi file in the Randomizer, it is saying 'rom name.cxi' is not a supported ROM type.

![image](https://user-images.githubusercontent.com/74762331/99774868-5b6d6600-2adc-11eb-9bd0-86f11ae6d92e.png)

**Comment by tom-overton** [comment] 2020-11-20 09:45
There are two possible reasons why you're getting this message:
1. You're running v3.1.0 or earlier, in which case 3DS games are not supported. We only added 3DS support starting in v4.0.0.
2. For whatever reason, the randomizer doesn't think that the game is a Pokemon game. Every 3DS game has a header that identifies what game it is; we use data from this header to make sure you're loading a Pokemon game into the randomizer (instead of something like Super Mario 3D Land). Your particular ROM might have a bad header which prevents us from detecting what game it is properly. I recommend trying a different ROM.

**Comment by ProphecyzZ** [comment] 2020-11-20 11:19
Using the latest version (believe it is 4.0.2).
Tried other games I dumped from my 3DS, same result. Could it be im dumping the game improperly?

**Comment by tom-overton** [comment] 2020-11-20 21:00
Yep, 4.0.2 is the latest version, so there's no issue there.
Interesting, what are you using to dump the games? Relatively recent versions of GodMode9? That's what I use and I haven't had any issues. If you want to validate your ROM, you can use [CTRTool](https://github.com/3DSGuy/Project_CTR/releases/tag/ctrtool-v0.7). Just run "ctrtool.exe [your ROM]" in the command line and it will spit out a ton of info. What you're looking for specifically is "Program id" and "Product code", since that's what the randomizer uses to validate the game. For Pokemon X, the randomizer is looking for this:
```
Program id:             0004000000055d00
Product code:           CTR-P-EKJA
```

**Comment by ProphecyzZ** [comment] 2020-11-21 13:23
The product code i am getting is:
CTR-U-EKJA
using the latest on GodMode9, just re downloaded it and updated it.

**Comment by tom-overton** [comment] 2020-11-21 13:59
Ah, I think I see the issue now. CTR-U-EKJA is the product code for the game's *update file*. You'll need to dump the base game to use with the randomizer. There are different methods of doing it depending on whether your game is a [cartridge](https://github.com/citra-emu/citra/wiki/Dumping-Game-Cartridges) or a [title you downloaded from the eShop](https://github.com/citra-emu/citra/wiki/Dumping-Installed-Titles). Try following those directions to dump the base game; it should be roughly 1.7 GB in size.

Note that if you dump the update file as a CIA instead of as a CXI, you can load it into the randomizer to make seeds that are compatible with your game update. In general, you need to make sure the version loaded in the randomizer is the same as the version you're running on your 3DS or in Citra; if you don't, you'll see unexpected behavior like certain things not randomizing or the game crashing on launch. We have a [page on the wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games) about some of the intricacies of the 3DS stuff if you'd like to read more.

**Comment by emg5322** [comment] 2020-12-06 18:05
Where in the code does it say which ROM codes it accepts? I'm trying to randomize Pokemon Y.

**Comment by tom-overton** [comment] 2020-12-06 22:55
They're listed in the [gen6_offsets.ini](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/blob/master/src/com/dabomstew/pkrandom/config/gen6_offsets.ini) file. I'll list all Gen 6 codes here too:
```
[X]
Game=CTR-P-EKJA
TitleId=0004000000055D00

[Y]
Game=CTR-P-EK2A
TitleId=0004000000055E00

[Omega Ruby]
Game=CTR-P-ECRA
TitleId=000400000011C400

[Alpha Sapphire]
Game=CTR-P-ECLA
TitleId=000400000011C500
```

**Comment by tom-overton** [comment] 2021-01-09 10:11
Closing this, as it's been a month-and-a-half since the OP appeared, so I assume my last message resolved the problem. If not, feel free to reopen.

**Closed by tom-overton** 2021-01-09 10:11 UTC

**Comment by spencer-best** [comment] 2021-07-01 23:49
Tom is that you? James's brother?

**Comment by spencer-best** [comment] 2021-07-01 23:49
Look Its still not working help me if you can please

**Comment by NJKD18** [comment] 2023-04-22 22:16
I'm trying to dump Alpha Sapphire but it keeps saying "CXI build failed".

**Comment by KittyMeOwl** [comment] 2024-05-16 01:09
I'm having this same problem but I'm using v4.6.0, whats going on?

**Comment by EitoGamin** [comment] 2025-02-23 09:37
so i am getting this error in 4.6.0 and ive tried .cia it says 3ds isnt supported on version 4.6?? i need help idk what is wrong, its not the same error but in 4.6 it is saying 3ds is not supported and has an error.
