### ISSUE TITLE
Top part of window not loading; unable to load ROM

### ISSUE THREAD

**Issue by rayquazamaster** [Ajarmar/universal-pokemon-randomizer-zx#67] opened 2020-11-21 22:55 UTC
<img width="1015" alt="Screen Shot 2020-11-21 at 5 54 42 PM" src="https://user-images.githubusercontent.com/74840339/99889393-a4c7cd80-2c22-11eb-9500-a7cd51420327.png">
The topmost part of the window isn't loading for me, and as a result I don't have the ability to load a ROM into the program. And therefore I don't exactly have a way to use it on any game.

**Comment by tom-overton** [comment] 2020-11-22 02:01
Closing this as a dupe of #35. Take a look at that issue for more details. The short answer is we know it's a problem, but you can get around it by changing the resolution on your Mac.

**Closed by tom-overton** 2020-11-22 02:01 UTC
